# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae28795d3dffc7a60f14b9c1ff347f4bd1eece80693f25555b56b44e9b49677e7201a3d05af0838625845257b9b2e1e113cfdbd72bb62d2d19cdf5f713094d46

test:
  secret_key_base: 3efc7cbdd548f1b1a1869f43b95e2f89a0b9f936ce68db632ac4981416a4bb5d12cf9dc0d5b6aa7208dba44ab8be18505a2c515f9f75b4c5288cb1479ca5d3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
